Lrp.prr.startpage
Amaliexiao/SemesterProject3 pull request #8
Opened 2023-11-14 10:06 UTC by loui22p

Initial startpage for project made in html and css and a bit js.

2023-11-14 12:25 UTC, Amaliexiao approved these changes

2023-11-16 07:56 UTC, Asbjoern09 requested changes

2023-11-16 07:56 UTC, Asbjoern09 commented on frontend/stylesheet.css
> +
Make the body margin 0, so that the page elements reach the whole page, look at top bar for example

2023-11-16 07:56 UTC, Asbjoern09 commented on frontend/index.html
> +        <p>Beer Brewer</p>
make this look good or remove it

2023-11-16 08:16 UTC, mariescheffmann approved these changes

2023-11-16 08:17 UTC, Asbjoern09 approved these changes
LGTM

2023-11-16 08:17 UTC, merged